### ISSUE TITLE
Links in code block requires escaping.

### ISSUE THREAD

**Issue by Magicloud** [haskell/haddock#1010]
`[title](url)` in normal place does not require `url` to be escaped (the `/` char). But if it is in `@ ... @` code block, I need to replace `/` with `\/` or `/` is removed in result.

**Comment by harpocrates** [comment]
I took the liberty of editing your comment, since GitHub was not displaying the `\` at all making the second sentence quite confusing. 😄 

Unfortunately, I can't replicate (on HEAD, Haddock that shipped with GHC 8.6.3, or Haddock that shipped with GHC 8.4.4). I suspect I'm not understanding the problem. Here's what I tried:

```haskell
module Foo where

-- | Some link not in a code block: [foldr](https://www.google.com/search?q=foldr)
--
-- @
-- Same link in a code block: [foldr](https://www.google.com/search?q=foldr)
-- @
--
bar :: Int
bar = 9
```

Based on your description, the link in the code block would need to be `https:\/\/www.google.com\/search?q=foldr` in order to render properly, but that's not the case!

Might you put together a simple Haskell module demonstrating the problem you are seeing?

**Comment by harpocrates** [comment]
Not at all, no need to apologize!

> Following 1st line shows correctly italiced string. And the 2nd line, I do not need to escape the `_` before yy to get a correct link.

Your seeing `_jjj_` rendered as italics? I can't seem to replicate that. As for `_[j_j](http://abc.com/_yy)_
`, what would you expect to be rendered? Note that single underscores aren't supposed to mean anything in Haddock's markup format (double underscores are used for bolded text).

For visual reference, this is how I see your examples rendered:

<img width="130" alt="screen shot 2019-01-30 at 3 48 56 pm" src="https://user-images.githubusercontent.com/10766081/52020570-99803c80-24a6-11e9-84cb-dfb877df7fd0.png">

What were you expecting instead?

**Comment by Magicloud** [comment]
Ah, my jj-s are github markdown. Just showing the "code". If you copy them in this dialog, and check preview, they are, "correctly" rendered. I think that is expected behavior, that URL in `()` does not interact with `_` outside.

**Comment by Magicloud** [comment]
![1548892301](https://user-images.githubusercontent.com/1886157/52020706-5321f080-252d-11e9-971d-354847d6617a.png)

**Comment by harpocrates** [comment]
Yes indeed, that is the expected behaviour! Thanks for clarifying 😄
