### ISSUE TITLE
GHC module documentation lacks hyperlinking since 8.4

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/haddock#1075]
[The current version of GHC.html on Hackage](https://hackage.haskell.org/package/ghc-8.6.5/docs/src/GHC.html) doesn't have hyperlinking inside it, except for the export list. It seems to be the case for all versions back to 8.4.1. In contrast, 8.2.2 (the last release in 8.2 series) is fine.

It's not clear what caused it. I opened a bug against GHC repository, but [Ben suggested](https://gitlab.haskell.org/ghc/ghc/issues/16994#note_216052) this may be a Haddock issue.

#1061 seems distantly relevant, but it seems to be triggered by recent changes. While the problem on Hackage is present since 8.4.

**Comment by harpocrates** [comment]
I believe this was fixed as part of the hyperlinker backend work that landed (is landing?) with the 8.8 release. The issue was confusion around some code which only lexed _after_ CPP ran (some multi-line string that isn't valid Haskell, but is when run through the pre-processor... 😄).

Can you still reproduce this in a clean GHC build? With Hadrian, you can do `./hadrian/build.sh docs-haddock` to build something analogous to wwhat is on Hackage.

**Comment by ulysses4ever** [comment]
> With Hadrian, you can do `./hadrian/build.sh docs-haddock` to build something analogous to wwhat is on Hackage.

I tried that and ran into the [llvm-target Hadrian bug](https://github.com/haskell/haddock/issues/1061#issuecomment-492027102). Maybe it's time to report it after all…

**Comment by harpocrates** [comment]
I’m pretty sure here are some nightly doc artifacts hosted somewhere. I forget where though. Someone or irc would know though.

**Comment by ulysses4ever** [comment]
There was a simple workaround -- to build GHC in full (`./hadrian/build.sh -j`) first, as noted by Ryan G. Scott in #1061, but I missed somehow on the first read of that thread.

I can confirm hyperlinking is not an issue when GHC built locally (with default flags). Hopefully, 8.8.1 will have proper docs on Hackage after the break of two full releases (8.6 and 8.4).
