### ISSUE TITLE
please make sure all contributors/members have 2fa enabled on their gh accounts

### ISSUE THREAD

**Issue by cartazio** [haskell/haddock#1137]
the haskell github org will be enabling 2fa sometime next week, possibly monday!
cc @harpocrates  et al

**Comment by harpocrates** [comment]
@cartazio since you are able to enable 2fa for the org, you must have the permissions to set default branches for repositories in the org too. Could you set Haddock's default branch to be `ghc-8.10`? 😃 

Also, is it OK if Haddock uses Github actions for windows CI? I'd prefer to use AppVeyor, but I again lack the permissions to set the webhook. See the maddening thread at https://github.com/haskell/haddock/pull/1096.

Finally, has 2fa been set by now? Can we close this?

**Comment by cartazio** [comment]
Sure on 2fa

Also open a ticket about the perms for which things you need added to
hooked up for haddocks etc and cc me emily and hvr and we will iterate on
ci suport needs there?

**Comment by harpocrates** [comment]
Thanks, I'll open a ticket! Closing this issue then.
