### ISSUE TITLE
Bold syntax doesn't render correctly when text flows over one lines.

### ISSUE THREAD

**Issue by malteneuss** [haskell/haddock#1450]
Bold long text that spans over one line isn't rendered as bold, at least with block comments:
```haskell
{- | 
__This 
doesn't work__
-}
```

However, it works when the text stays on one line:
```haskell
{- | 
__This works__
-}
```
Tested with Haddock version 2.24.2 within Stack version 2.7.3 x86_64 hpack-0.34.4 on NixOS 21.11, GHC version 8.10.7.

**Comment by stevehartdata** [comment]
This appears to be expected behavior. See [the relevant test](https://github.com/haskell/haddock/blob/e1e75e503291d194cdbe47cb161c9e754738b9e0/haddock-library/test/Documentation/Haddock/ParserSpec.hs#L381) for the parser. This has also been Haddock's behavior since bold support was added in ef9aa98d6ccbe79888c501f94c9aa6688520c28e.

**Comment by malteneuss** [comment]
How about adding a hint to the docs? I could add a PR in the next days.

**Comment by Kleidukos** [comment]
That would be fantastic
