### ISSUE TITLE
support for multiline text doctest properties

### ISSUE THREAD

**Issue by thielema** [haskell/haddock#1609]
Doctest supports multiline syntax `:{ .. :}` for doctest unit tests, e.g.

~~~~
>>> :{ runMyTest
   longArgumentA
   longArgumentB
   longArgumentC
:}
expected output
~~~~

but it does not support that syntax for doctest properties, that is

~~~~
prop> :{ runMyTest
   longArgumentA
   longArgumentB
   longArgumentC
:}
~~~~

We would like to support multiline syntax for properties in `doctest-extract`, though, which is currently blocked by missing support in Haddock. We have factored out the doctest parser to https://hackage.haskell.org/package/doctest-lib, thus haddock and doctest-extract and doctest could use the same parser.

See also: https://github.com/sol/doctest/issues/131

**Comment by Kleidukos** [comment]
Hi, thank you for this ticket, but Haddock now lives full-time in the GHC repository! 
Read more at https://discourse.haskell.org/t/haddock-now-lives-in-the-ghc-repository/9576.

Let me know if you feel it is still needed, and I'll migrate it. :)

**Comment by ruifengx** [comment]
As an end user, I still would like this feature to be implemented. Currently, multi-line doctest unit tests are actually not supported by Haddock; it just works by coincidence.

For the following doc comment:
```haskell
-- >>> :{
-- some
--   test
--   lines
-- :}
```
Haddock renders the first line (i.e., `:{`) as code (with a bold font), but the rest of lines as output text (with a normal font). Ideally, the code block should instead be written as follows:
```haskell
-- >>> :{
-- >>> some
-- >>>   test
-- >>>   lines
-- >>> :}
```
so as to indicate all these lines are test code instead of output texts, but Haddock would trim the leading whitespace, resulting in incorrect layout.

Anyway, I believe this issue is still relevant for Haddock and should be migrated to the GHC repo on GitLab. One of the few things I miss after returning to Haskell from Rust is the integration of doctests, and I sincerely hope this situation could improve over time.

**Comment by thielema** [comment]
It is implemented but seems to have been dropped due to the move of Haddock into GHC repository:
https://github.com/haskell/haddock/pull/1619
