### ISSUE TITLE
vimhelp backend updated for ghc-7.4.2

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#215]
**Original reporter**: _lars_e_krueger@<hidden>_

I included 2 patches in the attachment.

submission_20120929_ghc-7.4.1.patch applies to tag ghc_7.4.1-release
submission_20120929_ghc-7.4.2.patch applies to tag ghc_7.4.2-release

For some reasons I have haddock 2.10.0 together with ghc 7.4.2 on my system (Gentoo with haskell overlay). Hence, I prepared both patches

**Comment by gbaz** [comment]
@LarsEKrueger I suspect this was your PR, from ages ago. The patch files are well gone (due to the bug import process).  I also suspect that if you did want to pick this up in the future, the api would indeed be the right way these days. So I'm  closing this issue for the time being. If you did want to pick up changes to haddock that you think would help with integration efforts, future issues  and PRs are certainly very welcome!

**Comment by LarsEKrueger** [comment]
That's fine with me.
 

Dr. Lars Krueger

 
 

Gesendet: Mittwoch, 07. Februar 2018 um 05:30 Uhr
Von: gbaz <notifications@github.com>
An: haskell/haddock <haddock@noreply.github.com>
Cc: LarsEKrueger <lars_e_krueger@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [haskell/haddock] vimhelp backend updated for ghc-7.4.2 (#215)


@LarsEKrueger I suspect this was your PR, from ages ago. The patch files are well gone (due to the bug import process). I also suspect that if you did want to pick this up in the future, the api would indeed be the right way these days. So I'm closing this issue for the time being. If you did want to pick up changes to haddock that you think would help with integration efforts, future issues and PRs are certainly very welcome!
