### ISSUE TITLE
Double-clicking on a function name also selects "Source" on the right hand side

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#249]
**Original reporter**: _mail+haddock-trac@<hidden>_

This is because necessary whitespace is missing in the HTML.

Fix: https://github.com/nh2/haddock/compare/fix-source-selection-accidents

Thanks

**Comment by sjcjoosten** [comment]
This frustrated me too.. (after copy-pasting to plain text, it made me think that some type was called "TestSource" instead of "Test", and I couldn't find any documentation on TestSource). I'd fix it (for most browsers) by adding the following CSS will help fix this:
.link {
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
}
it is not standard CSS, nor does such CSS exist as far as I know. It will prevent the text "Source" form being copied in Chrome (tested), and probably in Firefox/Safari/IEMicrosoft as well (according to documentation).

Sorry for not making a pull request myself for this.

**Comment by Fuuzetsu** [comment]
If someone more versed wants to make a PR and confirm it doesn't break anything, I'm happy to take it.

**Comment by bgamari** [comment]
Seems like this one might also be easy to tick off.

**Comment by ad-si** [comment]
Can we please reopen this ticket?
This is still (again?) a problem in Chrome and derivatives like Brave! 🙈

PureScript has the same issue: https://github.com/purescript/purescript/pull/3002
