### ISSUE TITLE
make it easier to run profiled haddock executable

### ISSUE THREAD

**Issue by jwaldmann** [haskell/haddock#346]
it is hard to collect performance data because of
https://www.haskell.org/pipermail/haskell-cafe/2014-November/116758.html

I can build haddock like this:

```
cabal install --enable-executable-profiling haddock
```

and then, in my project,

```
cabal haddock --haddock-options='+RTS -p -h -RTS'
```

results in this error:

```
haddock: dist/build/tmp-22236/src/Inter/Wert.hs:1:14-28: You can't use
Template Haskell with a profiled compiler
```

For the project mentioned in Bug #345 , template Haskell is essential, and pervasive.

**Comment by Fuuzetsu** [comment]
I'll have to close unfortunately, it is simply the cases that you can not easily run profiled Haddock on code bases with TemplateHaskell due to GHC limitation and it's not something we can work around by. Apologies for leaving this issue hanging for so long. Probably the only way is to eliminate use of TH in the codebase first in whatever way as long as it compiles.
