### ISSUE TITLE
Hoogle export with GHC 7.10 has excessive square brackets.

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haddock#361]
In particular, I see the line:

    [Nothing] :: Maybe a

The square brackets are really odd. This is taken from the GHC 7.10 RC2 file.

**Comment by Fuuzetsu** [comment]
I minimum test case would be very welcome as usual.

**Comment by ndmitchell** [comment]
Grabbing GHC 7.10.0.20150123, I made the file `Foo.hs`:

    module Foo where
    data MaybeD a = NothingD | JustD a

And ran `haddock Foo.hs --hoogle`, but that failed with:

    haddock: internal error: expectJust getPackageDetails

I then tried:

    haddock Foo.hs --hoogle --package-name=foo --package-version=1

Which worked, but produced the Hoogle file containing the two lines:

    [NothingD] :: MaybeD a
    [JustD] :: a -> MaybeD a

This reports itself to be:

    $ haddock --version
    Haddock version 2.16.0, (c) Simon Marlow 2006
    Ported to use the GHC API by David Waern 2006-2008

Which is certainly an incorrect copyright year...

**Comment by ndmitchell** [comment]
Note this is a regression introduced after GHC 7.8.

**Comment by snoyberg** [comment]
I've run into the `expectJust` error message myself, and it looks like it should be a blocker for the GHC 7.10 release. @Fuuzetsu Am I overstating the severity of this issue? Do you have any thoughts on what's causing this bug?

**Comment by ndmitchell** [comment]
@snoyberg - how did you hit that issue? Is there some tool like Cabal than runs it? I was doing that for debugging, so not sure if anything "real" does it.

**Comment by snoyberg** [comment]
I ran `stackage nightly` with GHC 7.10, which runs `cabal haddock --hoogle` (and a few other options). I'll go and see if there's a minimal example of it.

**Comment by ndmitchell** [comment]
Does it fail if you omit the `--hoogle`? That's about the only thing you can take out of my example above.

**Comment by snoyberg** [comment]
--hoogle is the trigger to cause it to fail:

```
$ cabal haddock --hoogle
Running Haddock for acme-missiles-0.3...
Preprocessing library acme-missiles-0.3...
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: stm-2.4.4
Haddock coverage:
 100% (  2 /  2) in 'Acme.Missiles'
  75% (  3 /  4) in 'Acme.Missiles.STM'
  Missing documentation for:
    Module header
haddock: internal error: expectJust getPackageDetails
$ cabal haddock
Running Haddock for acme-missiles-0.3...
Preprocessing library acme-missiles-0.3...
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: stm-2.4.4
Haddock coverage:
 100% (  2 /  2) in 'Acme.Missiles'
  75% (  3 /  4) in 'Acme.Missiles.STM'
  Missing documentation for:
    Module header
Documentation created: dist/doc/html/acme-missiles/index.html
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.0.20150212
$ cabal --version
cabal-install version 1.22.0.0
using version 1.22.0.0 of the Cabal library 
```

**Comment by Fuuzetsu** [comment]
See https://github.com/haskell/haddock/issues/353 for `expectJust`

**Comment by snoyberg** [comment]
Can you clarify? Does that mean that this problem is fixed? If so, does GHC need to pull in an updated version of haddock?

**Comment by Fuuzetsu** [comment]
The flags are implemented in Haddock and I believe the change is on the 7.10 branch. What needs to happen is other tools (most likely cabal) need to learn to now use these. As @luite points out on #353 , the problem is that we can no longer expect to always be able to get the package name and version from the available databases so cabal needs to tell them to us explicitly instead. So the further fix needs to go into cabal. The thing is that as per https://github.com/haskell/cabal/issues/2297 , they want the change in `ghc-head` branch (GHC 7.11) but I've had no luck and then time in doing that. Presumably then it would get cherry-picked onto the release to come out with 7.10.

So now either I manage to update the submodule for GHC HEAD very soon and cabal implements a fix then backports to 7.10 branch (unlikely though I hear 7.10 has been pushed back again so who knows) OR we don't make it in time, 7.10 ships with cabal unable to use the flags and hoogle becomes broken until eventually new cabal with the fix is released.

IMHO cabal should tailor a patch based on what's on GHC 7.10 branch and in the future, when `ghc-head` is up to date we can patch that too but this is something for cabal folk to think about.

**Comment by snoyberg** [comment]
It looks like @bgamari is on top of fixing this, which is great. Ben: is GHC HQ aware of this bug? I'd really hate to have GHC 7.10.1 ship with this bug in place, I'd consider it a blocker. I can send an email to the GHC dev list if that will be useful.

**Comment by bgamari** [comment]
@snoyberg I absolutely agree; a release in this state would be quite unfortunate. Time is a bit tight until my defense but I can probably find some time to put towards a solution in the next few days as I'm waiting on instrumentation.

I'm not sure whether GHC HQ is aware of the issue but given the severity of the problem it wouldn't do any harm to advertise it widely.

**Comment by snoyberg** [comment]
OK, email sent.

**Comment by bgamari** [comment]
@snoyberg thanks!

**Comment by hvr** [comment]
Has there been any progress? We are supposed to cut the final GHC 7.10.1 today...

/cc @thoughtpolice

**Comment by Fuuzetsu** [comment]
No, no progress. The fixes for this and other hoogle issues will have to be made in separate Haddock release and users prompted to update.

**Comment by ndmitchell** [comment]
Great! I've just hacked in a temporary fix as the base library currently ships with lots of square bracket constructors, but I look forward to removing it in due course.
