### ISSUE TITLE
haddock-library on hackage with base < 4.8 bound breaks with ghc 7.10

### ISSUE THREAD

**Issue by markus1189** [haskell/haddock#366]
Hi,

is there a chance that somebody could upload a haddock-library version on hackage that does not have the `base < 4.8` version bound?  I am currently trying to install `pandoc` but it depends on `haddock-library` which fails to build because of this.

Cheers,
Markus

**Comment by Fuuzetsu** [comment]
Does `haddock-library` work with `base-4.8`? What's the error you're seeing, `pandoc` doesn't constrain `base` directly.

**Comment by markus1189** [comment]
The new git version of `haddock-library` `1.2` does work with ghc 7.10.  Pandoc currently constrains `haddock-library` to `==1.1`, which is not `haddock-library`'s fault, but as there is currently no version of `haddock-library` on hackage that works with 7.10 there is no point in changing it just now.

I don't know if 1.2 is ready for release but maybe a quick update for 1.1.* to work with ghc 7.10 would be nice :)

**Comment by Fuuzetsu** [comment]
GHC 7.10 is not out and I can not release `1.2` early because it is due to ship when 7.10 does as is rest of Haddock which will depend on it. I could maybe to maintenance `1.1` release but I now remembered that we never did make the constraint on `base` in the release. I think @hvr added it with the Hackage feature after it was uploaded for a reason I can no longer remeber but maybe he can remind us.

**Comment by hvr** [comment]
> I think @hvr added it with the Hackage feature after it was uploaded for a reason I can no longer remeber but maybe he can remind us.

...it was simply because it fails to compile with the current GHC 7.10.1 

it's a bit messy (since we now have multiple packages in a single Git repo and can't cleanly branch off with the current versioning scheme), but we can backport the changes needed into a new `haddock-library-1.1.x` Git branch... (or maybe it rather belongs into a `haddock-2.15.x` branch? that's why I don't like multiple packages in a single Git repo with diverging package versions...)

**Comment by mantkiew** [comment]
Any ETA for this fix? Many tools, such as, hsdev, hdocs, etc. cannot be installed due to this problem which breaks people's dev. env.

**Comment by Fuuzetsu** [comment]
Forgot about this but it has been fixed 53 minutes ago when I uploaded haddock-library-1.2 to hackage. Libraries which use it may need updating.

**Comment by mantkiew** [comment]
Thanks!

Yes, `hdocs` complains about:

    Expected type: InstalledInterface -> Map Name (Doc Name)
         Actual type: InstalledInterface -> DocMap Name

But that's an easy fix.

**Comment by hvr** [comment]
@mantkiew  sadly `hdocs` disregards the PVP by omitting *all* upper bounds on its build-deps, thus causing deliberate install-plan bitrotting :disappointed:
