### ISSUE TITLE
Hyperlinking type operator create #v link instead of #t link

### ISSUE THREAD

**Issue by christiaanb** [haskell/haddock#375]
Given the files:

`Bug2.hs`:
```haskell
{-# LANGUAGE TypeFamilies, TypeOperators #-}
module Bug2 where

type family (a :: *) + (b :: *) :: *
```

`Bug.hs`
```haskell
{-|
A link to 'Bug2.+'
-}
module Bug where
```

The command:
```
haddock --html Bug.hs Bug2.hs
```

Creates a link to in the haddock of `Bug` that is:
```
Bug2.html#v:-43-
```
instead of:
```
Bug2.html#t:-43-
```

I originally encountered this is when trying to create a link for `GHC.TypeLits.+`.

**Comment by Fuuzetsu** [comment]
OK, so it turns out this is effectivelly user error. When Haddock can't find something in scope, it defaults to `#v`. If in `Bug.hs` you `import Bug2`, you'll see that `#t` anchor is generated.

Now I realise what #253 was really about too: GHC changed a function so our defaults have shifted from `#v` to `#t`. You'll see on that ticket that the modules were not importing. I have now explicitly (i.e. I put a comment nearby) made `#v` the default for out-of-scope identifiers and we're using the GHC provided function. The reason those links work is because Haddock makes anchors anyway if and only if the identifier is qualified: that's how you're managing to go to the right module.

The lesson here is ‘import your damn identifiers before trying to refer to them!’. The only downside is redundant imports warning if you only refer to the identifiers in comments.

See 6dee5e814d1934cbed458894e01b4913452422e6 for details though it mostly re-iterates what I just said. I just wish it didn't take so long to investigate..

**Comment by christiaanb** [comment]
No such defaulting is mentioned in the user guide. Although it is understandable that it must default if it doesn't have any information on the kind of the identifier.

The user-guide just says:

> Referring to a Haskell identifier, whether it be a type, class, constructor, or function, is done by surrounding it with single quotes:

And then later:

> It is also possible to refer to entities that are not in scope in the current module, by giving the full qualified name of the entity:

So it isn't immediately clear from the user-guide that you _only_ refer to out-of-scope functions, and not types or classes.

**Comment by Fuuzetsu** [comment]
>No such defaulting is mentioned in the user guide.

Yes, it needs to be added/made more precise. After all I didn't know the rules of it until recently myself. So that is a documentation bug.

**Comment by janpath** [comment]
Just importing the qualifiers referred to may result in an import cycle. It would be great if there was a way to specify whether the identifier is from value or type scope. That could also be important where there an identifier exists in both scopes, though mostly that will be instances like `newtype A = A _`, so the type and the value link would lead to the same place anyway. Maybe the syntax could be `'type A'` or `'value A'`.

**Comment by harpocrates** [comment]
> Just importing the qualifiers referred to may result in an import cycle. It would be great if there was a way to specify whether the identifier is from value or type scope. That could also be important where there an identifier exists in both scopes, though mostly that will be instances like `newtype A = A _`, so the type and the value link would lead to the same place anyway. Maybe the syntax could be `'type A'` or `'value A'`.

Once Hi Haddock merges, I'll also merge https://github.com/haskell/haddock/pull/888. Note also that fully qualified identifiers will be linked even if they aren't imported. Please don't abuse this last fact though. 😄

**Comment by janpath** [comment]
> Note also that fully qualified identifiers will be linked even if they aren't imported. Please don't abuse this last fact though.

What do you mean? Is there some way to use this for a workaround for my problem? I know I can link to non-imported entities by fully qualifying them, but the problem is that Haddock just assumes I want to link to a value-level term when actually I want to link to a type-level term. #888 solves this but I do not get the rest of your comment. Furthermore, is it considered bad practice to refer to non-imported identifiers? What is abusing this behaviour?

**Comment by harpocrates** [comment]
> What do you mean? Is there some way to use this for a workaround for my problem? I know I can link to non-imported entities by fully qualifying them, but the problem is that Haddock just assumes I want to link to a value-level term when actually I want to link to a type-level term. #888 solves this but I do not get the rest of your comment.

I was trying to reply to "Just importing the qualifiers referred to may result in an import cycle", but clearly I've misunderstood what you mean.

> Furthermore, is it considered bad practice to refer to non-imported identifiers? What is abusing this behaviour?

Again, I think I misunderstood your comment about qualifying identifiers. However, I'll still answer the first part of your question: It's just more brittle.

If you refer to non-imported identifiers, Haddock will create a link to whatever you claim exists without checking that it does. For instance, the following generates a completely bogus link (without even a warning!)

```haskell
module UnimportedLink where

-- | A link to 'Nonsense.But.Qualified.foo'
bogus :: ()
bogus = ()
```

However, if instead you leave the identifier unqualified, Haddock will warn you that the identifier doesn't exist and won't pollute your output with a bogus link (it'll just monospace `foo`):

```haskell
module PlainLink where

-- | A link to 'foo'
bogus :: ()
bogus = ()
```

Moral: if Haddock can resolve your identifiers it can warn you when you've made a mistake.
