### ISSUE TITLE
Typeclass instance links incorrect for base-4.8.0.0

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/haddock#383]
I'm not sure if this is Haddock's fault (it may be similar to #372), but I'll file an issue just in case. Currently, several typeclass instance hyperlinks that Haddock generated for [`base-4.8.0.0`](http://hackage.haskell.org/package/base-4.8.0.0) go to the wrong modules. As an example, the instance link for `Functor STM` in [`Data.Functor`](http://hackage.haskell.org/package/base-4.8.0.0/docs/Data-Functor.html#t:Functor) currently links to [`GHC.Base`](http://hackage.haskell.org/package/base-4.8.0.0/docs/src/GHC-Base.html#line-628) (where `Functor` is defined); however, the actual instance is located in [`GHC.Conc.Sync`](http://hackage.haskell.org/package/base-4.8.0.0/docs/src/GHC-Conc-Sync.html#line-628) on line 628 (the line number, at least, seems to be correct, but the module is wrong).

**Comment by Fuuzetsu** [comment]
As someone who implemented these links, what do you think @JPMoresmau ?

I also don't know if it's our fault or GHC fault. I'll leave it open until I have time for it or some kind soul comes along and resolves it first.

**Comment by JPMoresmau** [comment]
It's our fault, I think. When we generate the source URL, we use the template given by Cabal, which is `src/%{MODULE/./-}.html#line-%{LINE}`. And MODULE is the module of the declaration, so in fact the links only work if the instance is defined in the same module as the declaration. For instances we have the SrcSpan, but its file name is not used by the template! That's why we end up with the correct line but the incorrect file.

What's the best way to correct? We could transform the module of the declaration for instances (take the file name, remove src at the start, transform / into -, hope for the best), or have another template for instances, which would cause a change in Cabal also.

**Comment by JPMoresmau** [comment]
No, sorry, we should be able to pull the relevant DocName from the instHead, I'll investigate.
