### ISSUE TITLE
Build haddock executable with `-threaded`

### ISSUE THREAD

**Issue by manny-fp** [haskell/haddock#399]
In an internal project, there is some Template Haskell that requires the multithreaded RTS to run.  Running haddock on this code fails:

```
Haddock coverage:

src/My/Module.hs:60:3:
    Exception when trying to run compile-time code:
      user error (RTS doesn't support multiple OS threads (use ghc -threaded when linking))
    Code: template-haskell:Language.Haskell.TH.Quote.quoteExp
            z "foo"
```

Building the `haddock` executable with `--ghc-options=-threaded` seems to fix this.

Would there be any disadvantage to adding `-threaded` to haddock.cabal's ghc-options?  If a simple example would be helpful, let me know and I'll put one together.

(this is with GHC 7.8.4 on Linux x86_64, in case it's relevant)

**Comment by Fuuzetsu** [comment]
>In an internal project, there is some Template Haskell that requires the multithreaded RTS to run. 

Sounds cool and terrifying at the same time.

>Would there be any disadvantage to adding -threaded to haddock.cabal's ghc-options?

I think adding `-threaded` should be fine but at the same time I'm not an expert here: I suspect there might be a reason why the threaded RTS is not used by default for every program out there. I'd be inclined to just enable it and if someone has a problem then they can complain and give their reasons against it.

> If a simple example would be helpful, let me know and I'll put one together.

It would be useful if only to confirm myself that the flag is taking effect and making a difference. The smaller example the better of course.

>(this is with GHC 7.8.4 on Linux x86_64, in case it's relevant)

Current (and most likely next) version of Haddock works with 7.10.x only so I would not expect most people using 7.8.4 ever see that flag on by default. But if you care a lot then I could consider making a minor Haddock 2.14 release that adds the flag and only that so that 7.8.x users can just use that. Personally I'd prefer if people upgrade their compiler version though understandably that's not always an option. But this paragraph applies to pretty much any changes we make so it is just a general notice rather than anything specific to this issue.

**Comment by manny-fp** [comment]
Thanks, here's a PR that includes a simple test (just tries to run `forkOS` in a TH splice): #400.  We're fine waiting for the next GHC release, we have a workaround in place until then.
