### ISSUE TITLE
Improve formatting for record style GADT declarations

### ISSUE THREAD

**Issue by alanz** [haskell/haddock#461]
See https://ghc.haskell.org/trac/ghc/ticket/11028#comment:40

At the moment (f4ef2548954bedf26674adc7a06574e718898d19) a GADT declaration with record syntax is represented in haddock as 

``` haskell
    CmmCondBranch :: {..} -> CmmNode O C
        cml_pred :: CmmExpr
        cml_true, cml_false :: !Label
        cml_likely :: Maybe Bool
```

for

``` haskell
    CmmCondBranch :: {              -- conditional branch
        cml_pred :: CmmExpr,
        cml_true, cml_false :: ULabel,
        cml_likely :: Maybe Bool    -- likely result of the conditional,
                                    -- if known
    } -> CmmNo O C
```

Change the haddock format to reflect the source format, by adding braces and moving the return type to the end.

**Comment by harpocrates** [comment]
Fixed in aa33be50e6292875b6afea8f97980c3a6e76ed87. The [latest GHC docs](http://hackage.haskell.org/package/ghc-8.6.1/docs/CmmNode.html) reflect it too:

<img width="425" alt="screen shot 2018-12-21 at 11 35 53 am" src="https://user-images.githubusercontent.com/10766081/50360361-9f344b00-0514-11e9-987e-90e619cff429.png">
