### ISSUE TITLE
Haddock's resource directory ... does not exist!

### ISSUE THREAD

**Issue by jwaldmann** [haskell/haddock#519]
I have `cabal haddock` (and `stack haddock`) failing with

```
Haddock's resource directory (/home/___/software/haskell/haddock/.cabal-sandbox/share/x86_64-linux-ghc-7.10.3/haddock-api-2.16.2) does not exist!
```

I have no idea how haddock thinks that this should be its `resource directory`, and what it needs it for. I do not see this concept mentioned in `haddock -v|grep resource`. The haddock I am using is quite  elsewhere:

```
which haddock
/opt/ghc/stable/bin/haddock
```

because I configured ghc with `--prefix=/opt/ghc/ghc-7.10.3` and `stable` is a symlink to that.

Is haddock reading some stale dotfile?

**Comment by jwaldmann** [comment]
OK, I could work around this by removing/re-installing/re-compiling half of the world ... but I still don't know what was happening.

**Comment by ezyang** [comment]
When this happens to me, I find a resource directory that is known good and create a symlink to it (or copy paste the files to it). If you installed Haddock "normally", the resource files should have been installed to that directory.

**Comment by harpocrates** [comment]
This is definitely not a bug in Haddock (since Haddock lists the resource files in its `haddock-api.cabal`):

https://github.com/haskell/haddock/blob/8964666efc4d4ab9756a83d16a02115a38744408/haddock-api/haddock-api.cabal#L20-L39

For people running into this issue:

 * if you installed Haddock from `cabal`, `stack`, or used `haddock` bundled with a GHC/GHCJS/etc installation (the usual case), the bug is upstream with how resource files are handled

  * if you built the Haddock binary yourself (for instance with `v2-build`), consider:

       * installing the binary properly (recommended if you intend to use this binary later)
       * symlinking the `resource` folder to wherever it is you are calling Haddock
       * invoking Haddock with `--lib=<path-to-resource-folder>`
