### ISSUE TITLE
LexParseRn.hs: non-exhaustive pattern match

### ISSUE THREAD

**Issue by Profpatsch** [haskell/haddock#553]
```
haddockPhase
Running Haddock for wai-3.2.1.1...
Warning: The program 'hscolour' version >=1.8 is required but it could not be
found.
Preprocessing library wai-3.2.1.1...
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: bytestring-builder-0.10.8.1.0

Network/Wai.hs:97:1: Warning:
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
Haddock coverage:
  75% (  6 /  8) in 'Network.Wai.Internal'
  Missing documentation for:
     (Network/Wai/Internal.hs:98)
    Response (Network/Wai/Internal.hs:119)
  98% ( 47 / 48) in 'Network.Wai'
  Missing documentation for:
    Response (Network/Wai/Internal.hs:119)
haddock: internal error: src/Haddock/Interface/LexParseRn.hs:(87,12)-(139,59): Non-exhaustive patterns in case
```

**Comment by mpickering** [comment]
How am I meant to reproduce this? From what I can see the pattern match is actually exhaustive so without any reproduction instructions I don't know how to make any progress.

**Comment by Profpatsch** [comment]
I’m sorry, I’ve been trying to reproduce this with a normal setup; will try again next week.

**Comment by Profpatsch** [comment]
I found out where exactly that problem happens:

```sh
$ cabal configure --ghjs
Configuring wai-3.2.1.1...

$ cabal haddock
Running Haddock for wai-3.2.1.1...
Preprocessing library wai-3.2.1.1...
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: bytestring-builder-0.10.8.1.0
Haddock coverage:
  75% (  6 /  8) in 'Network.Wai.Internal'
  Missing documentation for:
     (Network/Wai/Internal.hs:98)
    Response (Network/Wai/Internal.hs:119)

Network/Wai.hs:97:1: Warning:
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
  98% ( 47 / 48) in 'Network.Wai'
  Missing documentation for:
    Response (Network/Wai/Internal.hs:119)
haddock: internal error: src/Haddock/Interface/LexParseRn.hs:(87,12)-(139,59): Non-exhaustive patterns in case
```

It doesn’t happen when it’s configured without `--ghcjs`.

**Comment by harpocrates** [comment]
I'm closing this since:

  * the only version of `haddock-api` on Hackage where `src/Haddock/Interface/LexParseRn.hs:(87,12)-(139,59)` corresponds to a match is `2.16.1`
  * that version requires `haddock-library = 1.2.*` and the only matching versions on Hackage are `1.2.0` and `1.2.1`
  * for both of those versions, the pattern match is exhaustive

---

So then how did this happen? After some git sleuthing, here is my theory:

The version of `haddock-library` that `haddock-api` was compiled against was one that was built from source and not Hackage! There was a brief time after `haddock-library-1.2.1` was released to Hackage and before the version was bumped to `haddock-library-1.4.1` during which one could've installed from source a version of `haddock-library` which would have claimed to be `1.2.1` but for which the pattern match in `haddock-api-2.16.1` would not have been exhaustive (`DocMathInline` was added during this time).

In any case, no longer an issue.
