### ISSUE TITLE
spliceUrl: UnhelpfulSpan

### ISSUE THREAD

**Issue by ChrisPenner** [haskell/haddock#565]
Hi there, I made a few small changes to my app and now haddock is failing to build with

```
    Warning: Rasa.Internal.Editor: could not find link destinations for:
        extState
    Warning: Rasa.Internal.Action: could not find link destinations for:
        extState
    haddock: internal error: spliceURL UnhelpfulSpan
    CallStack (from HasCallStack):
      error, called at utils/haddock/haddock-api/src/Haddock/Backends/Xhtml/Utils.hs:79:9in main:Haddock.Backends.Xhtml.Utils
```

The project is here: https://github.com/chrispenner/rasa

Steps to reproduce:
- clone the repo
- run `stack haddock` on commit https://github.com/ChrisPenner/rasa/commit/9dc05d8fb8aae145cc70a9cb88059e4954ac697d

I found this old issue: https://github.com/haskell/haddock/issues/207 but it seems like that one was resolved, and I'm still seeing the problem.

I believe it's related to the fact that I'm exporting lenses generated in TH by [makeClassy](http://hackage.haskell.org/package/lens-4.15.1/docs/Control-Lens-TH.html#v:makeClassy) from the `lens` package. 

Anyone aware of how to resolve issues caused by this? Or am I incorrect in guessing that this is the problem? I'd love to help track this down, but the errors provided by haddock are less than helpful 😝

**Comment by shajra** [comment]
This has been fixed on the "ghc-head" branch:  b8e3380f80da15b1e384ff56f992baac3fd7f3ee.  Unfortunately, it's not in 8.0.1, so it's not hit Stackage users yet.  The fix is so simple, though, I'm wondering if I can sneak in the patch into the Nix build of my project without too much trouble.

**Comment by ChrisPenner** [comment]
Hrmm, okay thanks!

I'm using stack to build my project, and docs (I have multiple packages in the same project); is there a way that I can invoke `stack haddock` using the new version? I've added the following to stack.yaml:

```yaml
packages:
- location:
    git: https://github.com/haskell/haddock
    commit: b8e3380f80da15b1e384ff56f992baac3fd7f3ee
```

but of course `stack haddock` still uses its own version. I've also tried `stack exec haddock **/*.hs` But I don't believe it's understanding which modules are which properly.

**Comment by massysett** [comment]
This bit me last night.  Previous bugs say this happens when there are Template Haskell splices that do not contain type signatures, but I don't think I have any of those.  At any rate fixing this is beyond my expertise.

It seems Stack will not use the Haddock if it is local to the package.  Here is how I fixed it on my system (assumes `stack` is NOT using a system-wide GHC, which is the default on recent releases):

    cd .stack-work/install/x86_64-osx/lts-8.2/8.0.2/bin
    cp haddock ~/.stack/programs/x86_64-osx/ghc-8.0.2/lib/ghc-8.0.2/bin/haddock

That's for OS X; changes will be needed for Linux or Windows; you just have to make sure to replace the Haddock that ships with GHC.

I made a tag in my fork

https://github.com/massysett/haddock/releases/tag/fix-UnhelpfulSpan-bug

that contains the fix, along with a `stack.yaml` for GHC 8.0.2 so it should build on future dates notwithstanding Hackage changes.

**Comment by feuerbach** [comment]
We've also run into this at @nstack. A workaround is to disable the docs for that single module with

```
{-# OPTIONS_HADDOCK prune #-}
```

**Comment by Fuuzetsu** [comment]
A more heavy-handed but otherwise not-code-touching method is to disable source links; for `stack` you'll need https://github.com/commercialhaskell/stack/pull/3104

**Comment by Fuuzetsu** [comment]
by the way from what I can tell, there's a workaround in master for this (no longer crashes but you get no link either)

**Comment by harpocrates** [comment]
Closing as this has been fixed for a while now.
