### ISSUE TITLE
Haddock regression in GHC 8.0.1: redundant documentation for default signatures

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/haddock#567]
With this file:

```haskell
{-# LANGUAGE DefaultSignatures #-}
-- | Documentation for Bug
module Bug where

-- | Documentation for Foo
class Foo a where
  -- | Documentation for bar
  bar :: a -> String
  -- | Documentation for bar's default implementation
  default bar :: Show a => a -> String
  bar = show
```

If `haddock-2.16.1` (shipped with GHC 7.10.3) on it, then it renders like so:

![haddock-old](https://cloud.githubusercontent.com/assets/2364661/21656183/19b6d2bc-d28b-11e6-89e0-1fa30958f27e.png)

But if I run `haddock-2.17.2` (shipped with GHC 8.0.1) on it, then it renders like so:

![haddock-new](https://cloud.githubusercontent.com/assets/2364661/21656188/1e2cd4cc-d28b-11e6-9911-75dd170b4012.png)

I certainly wouldn't have expected the current behavior. The ideal would be one of the proposals in https://github.com/haskell/haddock/issues/439#issuecomment-135090049 (or, failing that, reverting back to the old behavior in `haddock-2.17.2`).

**Comment by harpocrates** [comment]
The problem of the duplicated docstring will be fixed in Haddock shipping with GHC 8.8 (fixed in 245aa215fd3f31b1dd49f9d0d084729bc7adb64b). The more general issue of supporting default method docstrings (instead of just ignoring them as we currently do) is tracked by  #30. 

Here is what `Bug` looks like:

<img width="479" alt="Screen Shot 2019-03-15 at 10 41 48 AM" src="https://user-images.githubusercontent.com/10766081/54451136-5a811000-470f-11e9-8796-efd81aa9c6ba.png">
