### ISSUE TITLE
Incorrect type signature (type variable captured)

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell/haddock#646]
https://hackage.haskell.org/package/lens-4.15.3/docs/Control-Lens-Internal-Context.html#t:Context

When expanding the `ComonadStore` instance for this data type, the following type signature is shown:

```haskell
pos :: Context a b a -> a
```

as an instantiation of this class method:

```haskell
pos :: ComonadStore s w => w a -> s
```

The `a`s here clearly clash, when they should not. The correct type signature is 

```haskell
pos :: Context a b c -> c
```

(Or, even better, given the `a ~ b` head)

```haskell
pos :: Context a a c -> c
```

where `c` is fresh. Thanks!

**Comment by alexbiehl** [comment]
Thank for reporting @mitchellwrosen. This seems to be the same issue as #613. 

I suspect `Haddock.Interface.Specialize` is at fault here. The issue is even mentioned [here](https://github.com/haskell/haddock/blob/master/haddock-api/src/Haddock/Interface/Specialize.hs#L221). I will take a look later.

**Comment by mitchellwrosen** [comment]
Yes, that's the same issue! Apologies - I searched for "capture" before filing. I'll close this in favor of #613. Cheers.
