### ISSUE TITLE
GHC 8.4.1-alpha panic (extractDecl)

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/haddock#735]
I originally observed this in [this Travis build](https://travis-ci.org/ekmett/ad/jobs/328314307#L1535). Here is a minimal way to reproduce the issue:

```haskell
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeFamilies #-}
module Bug (Scalar) where

class (Num (Scalar t)) => Mode t where
  type Scalar t
```

In `haddock-2.18.1` (the Haddock bundled with GHC 8.2.2), this works fine:

```
$ /opt/ghc/8.2.2/bin/haddock Bug.hs --html
Haddock coverage:
   0% (  0 /  1) in 'Bug'
  Missing documentation for:
    Module header
```

However, in `haddock-2.18.2` (the Haddock bundled with GHC 8.4.1-alpha), this panics:

```
$ /opt/ghc/8.4.1/bin/haddock Bug.hs --html
Haddock coverage:
haddock: panic! (the 'impossible' happened)
  (GHC version 8.4.0.20171222 for x86_64-unknown-linux):
        extractDecl

Ambiguous decl for Scalar in class:
    class (Num (Scalar t)) => Mode t where
      type Scalar t
      {-# MINIMAL #-}
Matches:
    []
Call stack:
    CallStack (from HasCallStack):
      callStackDoc, called at compiler/utils/Outputable.hs:1150:37 in ghc:Outputable
      pprPanic, called at utils/haddock/haddock-api/src/Haddock/Interface/Create.hs:1013:16 in main:Haddock.Interface.Create
```

**Comment by RyanGlScott** [comment]
This regression was introduced in aee89dcde08a80957b55e0872eff919a48cc13f9 (`Make better use of AvailInfo `).

**Comment by mpickering** [comment]
I also observed this. Thanks for reproducing Ryan.

**Comment by alexbiehl** [comment]
Thanks for the reproducer. I have an idea of what is wrong.

**Comment by alexbiehl** [comment]
https://github.com/haskell/haddock/commit/aee89dcde08a80957b55e0872eff919a48cc13f9 makes haddock more precise regarding what is exported and what is not. The panic here does not occur with ghc-8.2s haddock because the `Scalar` export gets lost on somewhere on the way when creating interfaces. Thus the documentation looks like this (it is empty): 
![image](https://user-images.githubusercontent.com/1876617/35142399-765475d0-fcfe-11e7-9b0f-659f56d51a1a.png)

We now use `AvailInfo`s to resolve export lists and it tries to extract `Scalar` from the type class with `extractDecl`. But `extractDecl` doesn't know how to handle associated type families! I will extend the code here which should fix the issues.

**Comment by alexbiehl** [comment]
@RyanGlScott I have prepared a fix. Now the documentation looks like this: 

![image](https://user-images.githubusercontent.com/1876617/35144495-fc4e1596-fd04-11e7-9061-1460a66a6a36.png)

Is this the desired outcome? I am wondering if we would want to have some "context" that this is an associated type for the `Mode` type class.

**Comment by RyanGlScott** [comment]
I'll leave my comments at https://github.com/haskell/haddock/pull/736.
