### ISSUE TITLE
style switcher for --built-in-themes is broken

### ISSUE THREAD

**Issue by gbaz** [haskell/haddock#810]
This is in released haddock 2.19.0. When we run with --built-in-themes we're supposed to get a style switcher menu. Clicking on this menu yields `ReferenceError: styleMenu is not defined`. Not sure, from browsing the source, why it isn't working. Likely something related to the js changes in the QuickJump work by @alexbiehl 

It would be good to fix this, although, arguably, this is the sort of was-well-intentioned feature that I don't see getting a lot of use (the fact that nobody complained thus far afaik, and I only noticed because I was explicitly testing features points to this), and it might be appropriate to just remove the flag. People can pick which style they want, but having docs able to hot-swap between them feels like gold-plating imho.

**Comment by mzero** [comment]
Drop it!

It was there because the change I was making in the Haddock style was very radical at the time, and there were already rumblings from some that they didn't want their pixels changed on bit, thank you very much.... So I did the work to enable a style sheet switcher, and I made a style sheet that replicated (mostly) the old look.

This was also well back in the day when people still harbored notions that a "user style sheet" could have any meaning on a modern site, and that users could or should be able to choose the styling of content. We now all know that this is absurd.
