### ISSUE TITLE
haddock segfaults

### ISSUE THREAD

**Issue by jchia** [haskell/haddock#837]
Summary: Haddock segfaults when I do 'stack haddock' on a new nightly-2018-05-22 project that has haskell-src-exts as a dependency.

Originally, I made an issue here: https://github.com/commercialhaskell/stack/issues/4036

Unfortunately, being unfamiliar with the intricacies of stack and cabal, I don't have a smaller test case than the following:

1. Start with a fresh installation (official stack 1.7.1 binary installed, no ~/.stack/ directory)
2. `stack new --resolver=nightly-2018-05-22 test`
3. `cd test`
4. Edit package.yaml, adding haskell-src-exts to dependencies.
5. `stack haddock` and witness the crash.

It's clear that haddock segfaulted, not merely exited with a regular failure code.

**Comment by RobertFischer** [comment]
I am seeing this, too.

**Comment by harpocrates** [comment]
The segfault (or hanging) behaviour is triggered in the Happy-generated `InternalParser.hs` file when generating hyperlinked sources. The actual bug is small, but the frustrating segfault/hanging behaviour is courtesy of GHC's `lexTokenStream`.

Besides disabling hyperlinked sources completely,  I'm not sure what you can do to work around this (here is yet another reason to want a module level way of hiding modules from the Hyperlinker backend).

**Comment by RobertFischer** [comment]
Thank you very much.

**Comment by noxecane** [comment]
This still segfaults with `haskell-src-exts`. This time I am using `lts-12.6` unlike the original complaint.

### Relevent versions
stack: `1.7.1`
ghc: `8.4.3`
haddock: `2.20.0`

It crashes exactly the same way @jchia described
