### ISSUE TITLE
Inconsistent link destination for ambiguous, fully qualified identifiers

### ISSUE THREAD

**Issue by sjakobi** [haskell/haddock#891]
Given

```
-- | 'Data.Monoid.First'
module Lib where

import Data.Monoid
```

haddock generates a link to the `First` **type** constructor.

If I remove the import statement, it links to the **data** constructor.

**Comment by harpocrates** [comment]
The second case (where we get a link to the data constructor) looks like subpar interaction between fallback cases. The divergence from the usual behaviour of defaulting to  type constructors is documented:

https://github.com/haskell/haddock/blob/532b209d127e4cecdbf7e9e3dcf4f653a5605b5a/haddock-api/src/Haddock/Interface/LexParseRn.hs#L110-L118

Perhaps we should include an extra warning when we produce a `DocIdentifierUnchecked`? After all, that only happens when a user refers to something that hasn't been imported...

**Comment by sjakobi** [comment]
Thanks Alec, I had forgotten about that explanation. It makes sense to me.

I don't think we should add a warning: Users are probably writing a fully qualified identifier _because_ it's not in scope. They wouldn't have any reasonable way to get rid of the warning.

**Comment by harpocrates** [comment]
We could suggest adding a namespace qualification if `choices` has more than one thing in it (ie. the name might be a value or a type).

**Comment by sjakobi** [comment]
> We could suggest adding a namespace qualification if choices has more than one thing in it (ie. the name might be a value or a type).

I think that would be rather onerous for the user. IMHO we should only emit warnings when it seems likely that haddock won't do what the user expects.
