### ISSUE TITLE
Build instructions in readme out of date

### ISSUE THREAD

**Issue by anchpop** [haskell/haddock#961]
I'm on the latest version of Stack. I run `stack init` like the readme says, and get an error complaining about not being able to find a resolver that meets the requirements. It seems it has an issue finding a resolver with `xhtml` in the range `>=3000.2.2 && <3000.3`.

**Comment by harpocrates** [comment]
The issue is that Stack does not yet have a resolver which contains all of Haddock's dependencies (Stack takes some time to catch up when new GHC versions are released). The only resolvers that currently run on `ghc-8.6` are nightlies and it looks like `xhtml` hasn't been added back yet (I don't know why).

The following might work `stack init --resolver nightly-2018-11-06 --solver`, but no promises.
