### ISSUE TITLE
Running haddock in reverse?

### ISSUE THREAD

**Issue by anchpop** [haskell/haddock#962]
Here is my understanding of how haddock works now:

Haddock takes some text like this:

```haskell
-- |The 'square' function squares an integer.
square :: Int -> Int
square x = x * x
```

And returns some HTML describing `square`.

I would like to sort of do this in the opposite direction. Given two inputs, 

```haskell
square :: Int -> Int
square x = x * x
```
and

```
"The 'square' function squares an integer."
```

I would like to retrieve:

```haskell
-- |The 'square' function squares an integer.
square :: Int -> Int
square x = x * x
```

This obviously is pretty easy if the only thing necessary is putting the documentation in front of a tld. But I would like to be able to do this with all the kinds of documentation Haddock supports (class methods, function arguments, etc.).

If this is not possible I would be interested in contributing this functionality. I think it would be useful for writing UIs to make it easier to write documentation. However I'm unfamiliar with the haddock code base so I might need a nudge in the right direction

**Comment by harpocrates** [comment]
> Here is my understanding of how haddock works now:
> 
> Haddock takes some text like this:
> 
> ```haskell
> -- |The 'square' function squares an integer.
> square :: Int -> Int
> square x = x * x
> ```
> 
> And returns some HTML describing `square`.

At a very high level, that is true. Under the hood, however, Haddock doesn't do much of the text-level processing. Instead, we depend on `ghc`-the-library to parse the code and comments. Most of Haddock's code is concerned with rendering nice looking HTML (and some other formats) as well as parsing and rendering _markup_ in the doc comments.

I'm not clear on the precise nature of the inputs for the functionality that you propose (for instance, how would one decide that the string `"The 'square' function squares an integer."` should be associated with the function `square` and not, say, the function `circle`?) or what end goal you have in mind.

Since you will need to parse and pretty-print Haskell code, you may want to depend on `ghc`-the-library, in which case Haddock's code might be a good example of setting up the necessary configuration options. Alternately, you could use [`haskell-src-exts`](https://hackage.haskell.org/package/haskell-src-exts) library, which has a much simpler API.

**Comment by harpocrates** [comment]
Closing for now, feel free to re-open with a more concrete request.
