### ISSUE TITLE
Type parameters are omitted when there are argument descriptions

### ISSUE THREAD

**Issue by Lysxia** [haskell/haddock#973]
This renders the quantifier:
```haskell
f :: forall a. a -> a
```

This doesn't:
```haskell
f :: forall a
  .  a  -- ^ my comment
  -> a
```

The type parameters are important for `TypeApplication`-heavy libraries but not so much for others. I think a good solution would be a compile-time switch to show/hide type parameters.

**Comment by harpocrates** [comment]
I think we should print the `forall` whenever it could impact user code involving `TypeApplications`. 

I'm a bit weary of compile-time switches because the reader has to first figure out which switches were enabled before really knowing what to make of the docs. Besides, almost all docs on Hackage are already built with the same options (those from `cabal haddock --haddock-for-hackage`).

One other suggestion I've heard is to make the `forall` expandable/collapsable by clicking on, say, the `::`.

**Comment by Lysxia** [comment]
I see, that makes sense; I like that last suggestion.
Thanks for the fix!
